### PR TITLE
Customize tab scroll

### LINKED ISSUE #43: ScrollintoView not working in chrome
**Describe the bug**
In the chartchooser, scrolling through keyboard arrows won't change the view to see the charts.

**To Reproduce**
1. Go to chart chooser onboarding section
2. Hit right key arrows to navigate through the charts
3. See Error

**Expected behavior**
The view should move alongside the keyboard arrow so that the chart is visible.

**Screenshots**
Kapture 2021-07-16 at 11 41 46

### PR DESCRIPTION
**Pull request by jahn96**
Fix #43 , #32 , #50 

## Changes
* Fixed size of the side bar getting bigger as the sidebar content gets bigger.
* Fixed scrollintoview not working in chrome
    * Recent version of chrome doesn't support smooth behavior per [this](https://stackoverflow.com/questions/61885401/scrollintoview-is-not-working-in-chrome-version-81-behaviour-smooth-is-not-hap)
* Fixed vertical scroll of customize mark screen.

## ScreenShot
Kapture 2021-07-20 at 10 45 31

## Testing
1. plot bifrost()
2. Select columns
3. Scroll through the recommended charts through arrow keys
4. Hit customize tab
5. See changes

### CODE REVIEW

File: src/components/BifrostReactWidget.tsx [hunk 1]
```diff
@@ -12,6 +12,11 @@ const globalStyles = (theme: any) => css`
   // Global styles for the widget
   //===========================================================
   .bifrost-widget {
+    width: calc(100vw - 200px);
```
Comment (Waidhoferj) [inline src/components/BifrostReactWidget.tsx:15]: Since the parent container now has an enforced width, we shouldn't have to do this anymore. Maybe try a percentage of the parent? Are you going for `100%`?

File: src/components/Sidebar/Sidebar.tsx [hunk 2]
```diff
@@ -63,6 +66,7 @@ const tabBarCss = css`
     border-bottom: none;
     width: calc(100% / 3);
     text-align: center;
+    overflow-x: auto;
```
Comment (Waidhoferj) [inline src/components/Sidebar/Sidebar.tsx:69]: We probably want the parent to strictly enforce its borders instead of using auto overflow.

File: src/components/VisualizationScreen.tsx [hunk 3]
```diff
@@ -10,10 +10,11 @@ const bifrostWidgetCss = css`
   // Element-based styles
   //===========================================================
   display: grid;
-  grid-template-columns: 675px minmax(450px, 600px);
+  grid-template-columns: 1fr minmax(450px, 600px);
```
Comment (Waidhoferj) [inline src/components/VisualizationScreen.tsx:13]: We probably want to keep a fixed value here that is wide enough to accommodate the color legend. If the sidebar and the graph get too far apart, its hard to interact between the two.

**Review by Waidhoferj — CHANGES_REQUESTED** [review]
Tested it out and works fairly well. However, there are some styling issues that make it not quite as adaptive to screen size or separate elements by too large of a margin.

**Review by Waidhoferj — APPROVED** [review]
LGTM

**Comment by Waidhoferj** [comment]
After merge conflicts are resolved its good to merge!
