### PR TITLE
Delete bug

### LINKED ISSUE #117: clicking x to delete not working
Can't delete adult_male pill in column selector

### PR DESCRIPTION
**Pull request by jahn96**
Fix #117 #109 #122

### CODE REVIEW

**Review by Waidhoferj — CHANGES_REQUESTED** [review]
After refreshing JuypterLab and restarting the kernel, I'm getting this error:
Screen Shot 2021-08-19 at 10 00 27 AM

**Comment by jahn96** [comment]
> After refreshing JuypterLab and restarting the kernel, I'm getting this error:
> Screen Shot 2021-08-19 at 10 00 27 AM

I changed the jupyter bifrost tracing. So, you might need to fetch changes from jupyter bifrost tracing.

File: src/components/Onboarding/ColumnSelectorSidebar.tsx [hunk 1]
```diff
@@ -207,7 +207,7 @@ export default function ColumnSelectorSidebar(props: { plotArgs: Args }) {
   function handleDelete(e: React.MouseEvent<HTMLButtonElement, MouseEvent>) {
     const updatedSet = new Set(selectedColumns);
     const selectedTag = (e.currentTarget as HTMLButtonElement).className.split(
-      '_'
+      /_(.+)/
     )[1];
 
     updatedSet.delete(selectedTag);
```
Comment (Waidhoferj) [inline src/components/Onboarding/ColumnSelectorSidebar.tsx:213]: Could we rewrite this function? It's generally bad practice to update the DOM directly in a React app because the source of truth should be the React State. A good way to start would be the following:
```
function handleDelete(column: string){...}
...
onClick={() => handleDelete(column)}
```

You can delete lines 215-218 because the logic on line 249 should already do this automatically : `checked={selectedColumns.includes(col)}`

**Review by Waidhoferj — CHANGES_REQUESTED** [review]
Works well! Just one change

**Review by Waidhoferj — APPROVED** [review]
LGTM
