### PR TITLE
Fixed axis slider issue

### LINKED ISSUE #83: Axis Sliders with Closed Sidebar
**Describe the bug**
Clicking on an axis with the sidebar closed will not show the axis slider and will throw an error

**To Reproduce**
1. Click on axis with sidebar closed
2. Notice error in console and no slider shows

**Expected behavior**
The user should be able to filter the field on the axis and see the effects without the sidebar being open. Another approach would be to open the sidebar when the axis is clicked.

**Screenshots**

https://user-images.githubusercontent.com/33008436/128405302-d711ad17-8bc4-4c1f-a707-01c30ea1bae7.mov

### PR DESCRIPTION
**Pull request by jahn96**
Fix #83
* Slider only opens for quantitative variable. For qualitative variable, it won't open the filter menu in the side bar as it isn't really necessary.
* Clicking axis will open the drop down for field in side bar to change it

### CODE REVIEW

File: src/components/Graph.tsx [hunk 1]
```diff
@@ -180,35 +180,27 @@ export default function Graph(props: GraphProps) {
...
+
     if (!encodingList) {
       newChannel = '';
     } else {
-      const pills = encodingList.getElementsByTagName('li');
-
+      const pills = encodingList.getElementsByClassName('graph-pill');
       if (pills) {
         Array.from(pills).forEach((pill) => {
+          console.log(pill.querySelectorAll('.pill-header span'));
```
Comment (Waidhoferj) [inline src/components/Graph.tsx:195]: Stray `console.log`

File: src/components/Graph.tsx [hunk 2]
```diff
@@ -53,7 +53,7 @@ export default function Graph(props: GraphProps) {
   const [selectedData, setSelectedData] = useModelState('selected_data');
   const [spec, setSpec] = useModelState('graph_spec');
   const [graphBounds, setGraphBounds] = useModelState('graph_bounds');
-  const [columnTypes] = useModelState('column_types');
+  // const [columnTypes] = useModelState('column_types');
```
Comment (Waidhoferj) [inline src/components/Graph.tsx:56]: Feel free to just take this out.

**Review by Waidhoferj — APPROVED** [review]
Nice update! Looks good.
