### PR TITLE
Box and whisker bug

### LINKED ISSUE #101: Box and Whisker Crash
**Describe the bug**
When an x-variable is deleted on a box and whisker plot, the graph does not update. Clicking anywhere after deleting the variable crashes the extension.

**To Reproduce**
1. Create a box and whisker chart with a quantitative variable on the x-axis and a categorical variable on the y-axis. In the Titanic dataset, "fare" on the x and "sex" on the y works well.
2. Delete x-pill. 
3. Click any button: extension will crash.

**Expected behavior**
When x-pill is deleted, the graph should update to reflect this. If it does not make sense in context, graph should disappear. It should not crash the extension.

**Screen Recording**
https://user-images.githubusercontent.com/83424843/129116519-4f928408-f8d2-4624-aad6-93f6ef03f0d6.mov

### PR DESCRIPTION
**Pull request by Waidhoferj**
Fixes #101

## Changes
- Fix boxplot crash
- Enforced all vega marks for the `vegaMarkEncodingMap`
- Fixed associated type errors

## Testing
See #101

### CODE REVIEW

File: src/modules/VegaEncodings.ts [hunk 1]
```diff
@@ -167,14 +167,19 @@ const bifrostVegaMark = [
...
   square: minimalEncoding,
   tick: minimalEncoding,
   line: minimalEncoding,
   bar: minimalEncoding,
   trail: minimalEncoding,
+  errorband: minimalEncoding,
+  boxplot: minimalEncoding,
+  errorbar: minimalEncoding,
+  area: minimalEncoding,
+  rect: minimalEncoding,
```
Comment (jahn96) [inline src/modules/VegaEncodings.ts:182]: circle, square, trail, area, and rect should be commented out because they are not in VegaMark

**Review by jahn96 — CHANGES_REQUESTED** [review]

**Comment by jahn96** [comment]
Other than this, it looks good!
