### PR TITLE
Fix #42

### LINKED ISSUE #42: Can't add a new variable when x and y columns are provided to plot method
**Describe the bug**
When we plot a bifrost graph with x and y variables and add a color variable through data tab in bifrost interface, it doesn't add color to the main graph.

**To Reproduce**
1. run `df.bifrost.plot(x=...., y=...)`
2. Select a mark.
3. Add color variable in data tab.
4. See error.

**Expected behavior**
It should add the color bar on the right side.

**Possible solution**
Add rest of the columns to encodings with channels with wild cards to querySpec.

**Screenshots**
Kapture 2021-07-16 at 11 19 48

**Additional context**
QuerySpec includes all columns of the dataframe.

### PR DESCRIPTION
**Pull request by jahn96**
## Changes
* Fixed #42 by saving types of columns on the backend.
* Fixed the given encoding to the suggested spec so that chart chooser only suggests the graph with the provided columns on the right axis.
* A few changes on select columns:
    1. Changed to use compass QL when the number of selected columns are less than four.
    2. If the number of selected columns is bigger than three, added the permutation of non-fixed columns to the fixed columns so that the size of the encodings becomes three.

## Testing
1. Plot bifrost without any parameters or with parameters
2. See the changes in chart chooser
3. See if you can add a new variable pill in data tab.

### CODE REVIEW

File: src/components/Sidebar/Tabs/VariablesTab.tsx [hunk 1]
```diff
@@ -45,11 +45,11 @@ const sortedEncodingList = [...vegaEncodingList];
 sortedEncodingList.sort();
 export default function VariablesTab() {
   const columns = useModelState('df_columns')[0];
+  const column_types = useModelState('column_types')[0];
```
Comment (Waidhoferj) [inline src/components/Sidebar/Tabs/VariablesTab.tsx:48]: Super minor, but this should be camelCase instead of snake_case.

File: src/widget.ts [hunk 2]
```diff
@@ -39,6 +40,7 @@ const bifrostModelPropDefaults = {
   suggested_graphs: [] as SuggestedGraphs,
   flags: {},
   plot_function_args: {} as Args,
+  column_types: {} as Record<EncodingInfo['field'], EncodingInfo['type']>,
```
Comment (Waidhoferj) [inline src/widget.ts:43]: Dude sweet use of types here!

**Review by Waidhoferj — APPROVED** [review]
One comment, but its totally optional
